"""add_news_categories_and_extend_newsitem

Revision ID: df512b1130c7
Revises: 627eb2fbc0c9
Create Date: 2025-06-04 09:29:06.774413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df512b1130c7'
down_revision: Union[str, None] = '627eb2fbc0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('news_item_category_association',
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('news_item_id', 'category_id')
    )
    op.add_column('news_items', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('news_items', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('news_items', sa.Column('cover_image_url', sa.String(length=1024), nullable=True))
    op.add_column('news_items', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('news_items', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_news_items_slug'), 'news_items', ['slug'], unique=True)
    op.create_index(op.f('ix_news_items_status'), 'news_items', ['status'], unique=False)
    op.drop_column('news_items', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('image_url', sa.VARCHAR(length=1024), nullable=True))
    op.drop_index(op.f('ix_news_items_status'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_slug'), table_name='news_items')
    op.drop_column('news_items', 'published_at')
    op.drop_column('news_items', 'status')
    op.drop_column('news_items', 'cover_image_url')
    op.drop_column('news_items', 'short_description')
    op.drop_column('news_items', 'slug')
    op.drop_table('news_item_category_association')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
